### ISSUE TITLE
Parameter slider hard to grab

### ISSUE THREAD

**Issue by lythro** [Zalia/Pacemaker#5]
I often lose the slider while dragging, any chance to make it bigger?

**Comment by Zalia** [comment]
which slider?

edit: since I found it impossible to lose the config sliders, I assume you mean the 'color' slider.
Unfortunately, thats not mine and I have no control over its size whatsoever. Also, I don't think it's irritating to lose grip of the slider when sliding too much in the vertical direction - and I'm saying that having it tested on the old samsung with the awfully buggy touch screen ;)

edit2: I just tested it on API 24 and found that all sliders now behave the same - i.e. it is impossible to lose grip unless you lift your finger.

**Comment by Zalia** [comment]
scratch all that. Upon further testing I noticed that the 'losing grip' issue is an issue coming from the scrollView (which is not active with the default mode on my virtual device, because the screen is big enough to fit the color picker -> not issues). Any vertical movement is immediately passed to the scrollview with the slider losing focus, which I have to admit, is rather annoying.

Fixed that by implementing a CustomLightnessSlider just like I did with the actual ColorPicker.
